requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "flask-login>=0.6.3",
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "openai>=1.76.2",
    "psycopg2-binary>=2.9.10",
    "discord-py>=2.5.2",
    "psutil>=7.0.0",
    "google-generativeai>=0.8.5",
]
